//! vkey_core — Pure Vietnamese typing engine in Rust.
//!
//! 2.0 (C2): foundation port từ Swift Engine/ sang Rust + C-ABI FFI.
//!
//! Coverage hiện tại (Phase 1):
//! - `State` — mirror của `TiengVietState` (chuKhongDau, dauThanh, dauMu, gachD).
//! - `Tone` / `Diacritic` enum.
//! - `push_char` — append + classify cơ bản.
//! - FFI surface `vkey_state_*`.
//!
//! TODO trong các phase tiếp theo:
//! - Phase 2: Validator — port `TiengVietValidator.needsRecovery`.
//! - Phase 3: Transformer — apply tone marks, diacriticals (kiểu mới/cũ).
//! - Phase 4: Telex / VNI engines + thay thế Swift engine khi 100% test parity.
//!
//! ## Build
//! ```
//! cargo build --release
//! # output: target/release/libvkey_core.a + .dylib
//! ```
//! Sau đó add `libvkey_core.a` vào Xcode "Link Binary With Libraries" và include
//! header generated bởi cbindgen ở `include/vkey_core.h`.

mod state;

pub use state::{Diacritic, State, Tone};

use std::os::raw::{c_char, c_int};

// ──────────────────────────────────────────────────────────────────────────
//  FFI surface — exported to Swift via `vkey_core.h` (generated by cbindgen).
// ──────────────────────────────────────────────────────────────────────────

/// Allocate a new empty `State` on the heap. Caller must free via `vkey_state_free`.
#[no_mangle]
pub extern "C" fn vkey_state_new() -> *mut State {
    Box::into_raw(Box::new(State::empty()))
}

/// Free a previously allocated `State`. Safe to call with null (no-op).
#[no_mangle]
pub extern "C" fn vkey_state_free(ptr: *mut State) {
    if ptr.is_null() {
        return;
    }
    unsafe {
        // Drop reconstructs ownership; Box is freed at end of scope.
        let _ = Box::from_raw(ptr);
    }
}

/// Push one ASCII character into the state.
/// Returns 0 on success, non-zero on error (null ptr).
#[no_mangle]
pub extern "C" fn vkey_state_push(state: *mut State, ch: c_char) -> c_int {
    if state.is_null() {
        return 1;
    }
    let s = unsafe { &mut *state };
    s.push_char(ch as u8 as char);
    0
}

/// Get the current `chuKhongDau` (raw input). Caller passes a buffer + capacity;
/// returns the number of bytes written (excluding null terminator), or -1 on error.
/// If `buffer` is too small, returns the required size (excluding null terminator);
/// nothing is written.
#[no_mangle]
pub extern "C" fn vkey_state_raw(
    state: *const State,
    buffer: *mut c_char,
    capacity: c_int,
) -> c_int {
    if state.is_null() || buffer.is_null() || capacity <= 0 {
        return -1;
    }
    let s = unsafe { &*state };
    let bytes = s.raw_bytes();
    if (bytes.len() + 1) as c_int > capacity {
        return (bytes.len() + 1) as c_int;
    }
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), buffer as *mut u8, bytes.len());
        // Null-terminate.
        *buffer.add(bytes.len()) = 0;
    }
    bytes.len() as c_int
}

/// Return 1 if the state currently needs recovery (invalid syllable),
/// 0 if valid, -1 on error.
///
/// Phase 1 stub: always returns 0 (parser-only port). Will be wired to the
/// real validator in Phase 2.
#[no_mangle]
pub extern "C" fn vkey_state_needs_recovery(state: *const State) -> c_int {
    if state.is_null() {
        return -1;
    }
    let s = unsafe { &*state };
    if s.needs_recovery() {
        1
    } else {
        0
    }
}

/// Get a 4-byte semver identifier (major << 16 | minor << 8 | patch). Useful
/// for the Swift side to verify ABI compatibility at runtime.
#[no_mangle]
pub extern "C" fn vkey_core_version() -> u32 {
    let major: u32 = 0;
    let minor: u32 = 1;
    let patch: u32 = 0;
    (major << 16) | (minor << 8) | patch
}
